version: '3.9'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    expose:
      - '3000'

  api2:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    expose:
      - '3000'

  nginx:
    image: nginx:stable
    depends_on:
      - api
      - api2
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}:80'
    depends_on:
      - api
      - api2

volumes:
  pgdata:
